version: "3.5"

services:
    
    laravel-app:
        build: 
            context: ./
            dockerfile: Dockerfile
        image: laravel_hubspot    
        container_name: laravel-app
        ports: 
            - 8081:8000
        working_dir: /var/www/html
        depends_on: 
           - mysql 

    mysql:
        image: mysql:8.0
        container_name: laravel-database
        restart: always
        environment:
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_ALLOW_EMPTY_PASSWORD=1
        ports:
            - 3307:3306
        volumes:
            - mysql-data:/var/lib/mysql
            
volumes:
      mysql-data: